
services:

  # Nginx Web Server
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: turismo-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - app_data:/var/www/html               # Usar o mesmo volume rápido
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - turismo
    depends_on:
      - php
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 5


  # PHP Application
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: turismo-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - app_data:/var/www/html                    # Local de execução (rápido)
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini   # (se usar)
      - ./:/host_project                          # Pasta do Windows
    networks:
      - turismo
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "pgrep php-fpm > /dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: sh -c "while :; do \
        rsync -av --delete \
        --exclude 'vendor/' --exclude 'node_modules/' \
        /host_project/ /var/www/html/; \
        sleep 2; \
        done & php-fpm"

  # PostgreSQL (ou troque por MySQL se quiser)
  postgres:
    image: postgres:15
    container_name: turismo-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: turismo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - turismo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d turismo"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MongoDB
  mongodb:
    image: mongo:6
    container_name: turismo-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - turismo
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis
  redis:
    image: redis:alpine
    container_name: turismo-redis
    ports:
      - "6379:6379"
    networks:
      - turismo
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  turismo:

volumes:
  pgdata:
  mongodata:
  app_data:
